update

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -68,11 +68,13 @@ jobs:
               OTHER_SERVICE="$GREEN_SERVICE"
           fi
 
-        #   # Check if the artifact exists
-        #   if [ ! -f $ARTIFACT_PATH ]; then
-        #       echo "Artifact $ARTIFACT_PATH not found!"
-        #       exit 1
-        #   fi
+          pwd
+
+          # Check if the artifact exists
+          if [ ! -f $ARTIFACT_PATH ]; then
+              echo "Artifact $ARTIFACT_PATH not found!"
+              exit 1
+          fi
 
           # Stop the running application
           sudo systemctl stop $SERVICE_NAME
@@ -87,7 +89,6 @@ jobs:
           #sudo tar -xzf $ARTIFACT_PATH -C $DEPLOY_PATH
           sudo cp -r $ARTIFACT_PATH/* $DEPLOY_PATH/
        
-
 
           # Restart the application
           sudo systemctl start $SERVICE_NAME
