remove check

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -68,11 +68,11 @@ jobs:
               OTHER_SERVICE="$GREEN_SERVICE"
           fi
 
-          # Check if the artifact exists
-          if [ ! -f $ARTIFACT_PATH ]; then
-              echo "Artifact $ARTIFACT_PATH not found!"
-              exit 1
-          fi
+        #   # Check if the artifact exists
+        #   if [ ! -f $ARTIFACT_PATH ]; then
+        #       echo "Artifact $ARTIFACT_PATH not found!"
+        #       exit 1
+        #   fi
 
           # Stop the running application
           sudo systemctl stop $SERVICE_NAME
